### ISSUE TITLE
`main-page` Refactor main-page for improved maintainability

### ISSUE THREAD

**Issue by thxforall** [decodedcorp/decoded-app#22]
### Description:
- Reorganize components for better reusability.
- Simplify state management for cleaner logic.
- Update directory structure to follow the team's conventions.

### Tasks:
- [ ] Split main-page components into smaller reusable parts (#22 refactor : refator-main-page).
- [ ] Split common components into smaller reusable parts (e.g, header) (#23 refactor : refactor-common-components).
- [ ] Update styles to align with the design system (#24 style : formatting-code).
