### ISSUE TITLE
[Front]Closed Beta Issue Tracking

### ISSUE THREAD

**Issue by cocoyoon** [decodedcorp/decoded-app#8]
## Description

Track for *TODO* task during **Beta** period 

## Tracking

- [x]  (이미지) 이미지위에 마우스를 올렸을 때 모든 점(위치)가 나왔으면 (#6)
- [x]  (전체) 사이드 여백 맞추기(#10)
- [x]  (전체) 텍스트 정렬 (버튼과 텍스트 정렬 같게) #5 
- [ ]  (search) article도 호버했을 때 확대되는 기능 넣기 (페이지 전체 통일성) 
- [x]  (search) title 과 content 사이 공백 20px 정도로 
- [x] Compact footer(#9)
- [x] 아이템 점들 눈에 띄게 변경 (#4)
- [x] 앱 전체적인 컬러 변경(#13)
- [x] 아이템 레이아웃 변경(#11)
- [x] 홈화면 아이템 둘러보기 서비스 컨셉보여줄 수 있는 UI 로 변경(#14)
- [x] 메인 페이지 디자인 수정(#17)
- [x] 요청 페이지(#18)
- [ ] 유저 저장 페이지(#15)
- [x] 제공 페이지(#29)
